import random

PERSONALITY_TRAITS = [
    # All traits are phrased to work in the context: "you are TRAIT"
    "abrasive",
    "adventurous",
    "aggressive",
    "altruistic",
    "ambitious",
    "anarchic",
    "apathetic",
    "arrogant",
    "authoritarian",
    "blunt",
    "brave",
    "callous",
    "calculating",
    "careless",
    "charismatic",
    "chauvinistic",
    "compassionate",
    "confident",
    "conservative",
    "conspiratorial",
    "controlling",
    "corrupt",
    "cowardly",
    "curious",
    "cynical",
    "decisive",
    "defiant",
    "deceptive",
    "diligent",
    "diplomatic",
    "dogmatic",
    "dominant",
    "eccentric",
    "egalitarian",
    "emotional",
    "elitist",
    "fanatical",
    "flirtatious",
    "forgiving",
    "friendly",
    "generous",
    "gossipy",
    "gullible",
    "hedonistic",
    "heretical",
    "hostile",
    "humble",
    "hypocritical",
    "idealistic",
    "impulsive",
    "inclusive",
    "indecisive",
    "innovative",
    "innocent",
    "jealous",
    "lazy",
    "libertine",
    "logical",
    "loyal",
    "loud",
    "manipulative",
    "martinet",
    "a martyr",
    "materialistic",
    "merciful",
    "meticulous",
    "mischievous",
    "moody",
    "naive",
    "nervous",
    "nihilistic",
    "obedient",
    "opportunistic",
    "optimistic",
    "outspoken",
    "paranoid",
    "passionate",
    "patriotic",
    "pessimistic",
    "perfectionist",
    "playful",
    "pragmatic",
    "prejudiced",
    "progressive",
    "provocative",
    "prudish",
    "quiet",
    "radical",
    "realistic",
    "rebellious",
    "reckless",
    "reserved",
    "ruthless",
    "sarcastic",
    "scheming",
    "secretive",
    "selfish",
    "sincere",
    "skeptical",
    "sloppy",
    "spiritual",
    "stable",
    "stoic",
    "strategic",
    "stingy",
    "submissive",
    "supportive",
    "suspicious",
    "tactful",
    "tactless",
    "timid",
    "tolerant",
    "traditionalist",
    "treacherous",
    "trusting",
    "trustworthy",
    "unmotivated",
    "untrustworthy",
    "vengeful",
    "vindictive",
    "volatile",
    "workaholic",
    "worldly",
    "xenophobic",
    "zealous"
]

def pick_random_personality() -> str:
    return random.choice(PERSONALITY_TRAITS)

def pick_multiple_personalities(n) -> list[str]:
    """Return a list of n unique random personality traits."""
    if n > len(PERSONALITY_TRAITS):
        raise ValueError("n exceeds the number of available personality traits.")
    return random.sample(PERSONALITY_TRAITS, n)